# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

    orderer.example.com:
        container_name: orderer.example.com
        image: hyperledger/fabric-orderer:$IMAGE_TAG
        environment:
          - ORDERER_GENERAL_LOGLEVEL=INFO
          - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
          - ORDERER_GENERAL_GENESISMETHOD=file
          - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
          - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
          - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - orderer.example.com:/var/hyperledger/production/orderer
        ports:
          - 7050:7050
    peer0.org1.example.com:
      container_name: peer0.org1.example.com
      environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 7051:7051
      - 7053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org1.example.com:/var/hyperledger/production
    peer0.org2.example.com:
      container_name: peer0.org2.example.com
      environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 8051:7051
      - 8053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org2.example.com:/var/hyperledger/production
    peer0.org3.example.com:
      container_name: peer0.org3.example.com
      environment:
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_ADDRESS=peer0.org3.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 9051:7051
      - 9053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org3.example.com:/var/hyperledger/production
    peer0.org4.example.com:
      container_name: peer0.org4.example.com
      environment:
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_ADDRESS=peer0.org4.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org4.example.com:7051
      - CORE_PEER_LOCALMSPID=Org4MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 10051:7051
      - 10053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org4.example.com:/var/hyperledger/production
    peer0.org5.example.com:
      container_name: peer0.org5.example.com
      environment:
      - CORE_PEER_ID=peer0.org5.example.com
      - CORE_PEER_ADDRESS=peer0.org5.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org5.example.com:7051
      - CORE_PEER_LOCALMSPID=Org5MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 11051:7051
      - 11053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org5.example.com/peers/peer0.org5.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org5.example.com:/var/hyperledger/production
    peer0.org6.example.com:
      container_name: peer0.org6.example.com
      environment:
      - CORE_PEER_ID=peer0.org6.example.com
      - CORE_PEER_ADDRESS=peer0.org6.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org6.example.com:7051
      - CORE_PEER_LOCALMSPID=Org6MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 12051:7051
      - 12053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org6.example.com:/var/hyperledger/production
    peer0.org7.example.com:
      container_name: peer0.org7.example.com
      environment:
      - CORE_PEER_ID=peer0.org7.example.com
      - CORE_PEER_ADDRESS=peer0.org7.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org7.example.com:7051
      - CORE_PEER_LOCALMSPID=Org7MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 13051:7051
      - 13053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org7.example.com/peers/peer0.org7.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org7.example.com:/var/hyperledger/production
    peer0.org8.example.com:
      container_name: peer0.org8.example.com
      environment:
      - CORE_PEER_ID=peer0.org8.example.com
      - CORE_PEER_ADDRESS=peer0.org8.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org8.example.com:7051
      - CORE_PEER_LOCALMSPID=Org8MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 14051:7051
      - 14053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org8.example.com/peers/peer0.org8.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org8.example.com:/var/hyperledger/production
    peer0.org9.example.com:
      container_name: peer0.org9.example.com
      environment:
      - CORE_PEER_ID=peer0.org9.example.com
      - CORE_PEER_ADDRESS=peer0.org9.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org9.example.com:7051
      - CORE_PEER_LOCALMSPID=Org9MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 15051:7051
      - 15053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org9.example.com/peers/peer0.org9.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org9.example.com:/var/hyperledger/production
    peer0.org10.example.com:
      container_name: peer0.org10.example.com
      environment:
      - CORE_PEER_ID=peer0.org10.example.com
      - CORE_PEER_ADDRESS=peer0.org10.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org10.example.com:7051
      - CORE_PEER_LOCALMSPID=Org10MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 16051:7051
      - 16053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org10.example.com/peers/peer0.org10.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org10.example.com:/var/hyperledger/production
    peer0.org11.example.com:
      container_name: peer0.org11.example.com
      environment:
      - CORE_PEER_ID=peer0.org11.example.com
      - CORE_PEER_ADDRESS=peer0.org11.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org11.example.com:7051
      - CORE_PEER_LOCALMSPID=Org11MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 17051:7051
      - 17053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org11.example.com/peers/peer0.org11.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org11.example.com:/var/hyperledger/production
    peer0.org12.example.com:
      container_name: peer0.org12.example.com
      environment:
      - CORE_PEER_ID=peer0.org12.example.com
      - CORE_PEER_ADDRESS=peer0.org12.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org12.example.com:7051
      - CORE_PEER_LOCALMSPID=Org12MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 18051:7051
      - 18053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org12.example.com/peers/peer0.org12.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org12.example.com:/var/hyperledger/production
    peer0.org13.example.com:
      container_name: peer0.org13.example.com
      environment:
      - CORE_PEER_ID=peer0.org13.example.com
      - CORE_PEER_ADDRESS=peer0.org13.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org13.example.com:7051
      - CORE_PEER_LOCALMSPID=Org13MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 19051:7051
      - 19053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org13.example.com/peers/peer0.org13.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org13.example.com:/var/hyperledger/production
    peer0.org14.example.com:
      container_name: peer0.org14.example.com
      environment:
      - CORE_PEER_ID=peer0.org14.example.com
      - CORE_PEER_ADDRESS=peer0.org14.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org14.example.com:7051
      - CORE_PEER_LOCALMSPID=Org14MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 20051:7051
      - 20053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org14.example.com/peers/peer0.org14.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org14.example.com:/var/hyperledger/production
    peer0.org15.example.com:
      container_name: peer0.org15.example.com
      environment:
      - CORE_PEER_ID=peer0.org15.example.com
      - CORE_PEER_ADDRESS=peer0.org15.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org15.example.com:7051
      - CORE_PEER_LOCALMSPID=Org15MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 21051:7051
      - 21053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org15.example.com/peers/peer0.org15.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org15.example.com:/var/hyperledger/production
    peer0.org16.example.com:
      container_name: peer0.org16.example.com
      environment:
      - CORE_PEER_ID=peer0.org16.example.com
      - CORE_PEER_ADDRESS=peer0.org16.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org16.example.com:7051
      - CORE_PEER_LOCALMSPID=Org16MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 22051:7051
      - 22053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org16.example.com/peers/peer0.org16.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org16.example.com:/var/hyperledger/production
    peer0.org17.example.com:
      container_name: peer0.org17.example.com
      environment:
      - CORE_PEER_ID=peer0.org17.example.com
      - CORE_PEER_ADDRESS=peer0.org17.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org17.example.com:7051
      - CORE_PEER_LOCALMSPID=Org17MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 23051:7051
      - 23053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org17.example.com/peers/peer0.org17.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org17.example.com:/var/hyperledger/production
    peer0.org18.example.com:
      container_name: peer0.org18.example.com
      environment:
      - CORE_PEER_ID=peer0.org18.example.com
      - CORE_PEER_ADDRESS=peer0.org18.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org18.example.com:7051
      - CORE_PEER_LOCALMSPID=Org18MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 24051:7051
      - 24053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org18.example.com/peers/peer0.org18.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org18.example.com:/var/hyperledger/production
    peer0.org19.example.com:
      container_name: peer0.org19.example.com
      environment:
      - CORE_PEER_ID=peer0.org19.example.com
      - CORE_PEER_ADDRESS=peer0.org19.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org19.example.com:7051
      - CORE_PEER_LOCALMSPID=Org19MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 25051:7051
      - 25053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org19.example.com/peers/peer0.org19.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org19.example.com:/var/hyperledger/production
    peer0.org20.example.com:
      container_name: peer0.org20.example.com
      environment:
      - CORE_PEER_ID=peer0.org20.example.com
      - CORE_PEER_ADDRESS=peer0.org20.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org20.example.com:7051
      - CORE_PEER_LOCALMSPID=Org20MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 26051:7051
      - 26053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org20.example.com/peers/peer0.org20.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org20.example.com:/var/hyperledger/production
    peer0.org21.example.com:
      container_name: peer0.org21.example.com
      environment:
      - CORE_PEER_ID=peer0.org21.example.com
      - CORE_PEER_ADDRESS=peer0.org21.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org21.example.com:7051
      - CORE_PEER_LOCALMSPID=Org21MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 27051:7051
      - 27053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org21.example.com/peers/peer0.org21.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org21.example.com:/var/hyperledger/production
    peer0.org22.example.com:
      container_name: peer0.org22.example.com
      environment:
      - CORE_PEER_ID=peer0.org22.example.com
      - CORE_PEER_ADDRESS=peer0.org22.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org22.example.com:7051
      - CORE_PEER_LOCALMSPID=Org22MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 28051:7051
      - 28053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org22.example.com/peers/peer0.org22.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org22.example.com:/var/hyperledger/production
    peer0.org23.example.com:
      container_name: peer0.org23.example.com
      environment:
      - CORE_PEER_ID=peer0.org23.example.com
      - CORE_PEER_ADDRESS=peer0.org23.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org23.example.com:7051
      - CORE_PEER_LOCALMSPID=Org23MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 29051:7051
      - 29053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org23.example.com/peers/peer0.org23.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org23.example.com:/var/hyperledger/production
    peer0.org24.example.com:
      container_name: peer0.org24.example.com
      environment:
      - CORE_PEER_ID=peer0.org24.example.com
      - CORE_PEER_ADDRESS=peer0.org24.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org24.example.com:7051
      - CORE_PEER_LOCALMSPID=Org24MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 30051:7051
      - 30053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org24.example.com/peers/peer0.org24.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org24.example.com:/var/hyperledger/production
    peer0.org25.example.com:
      container_name: peer0.org25.example.com
      environment:
      - CORE_PEER_ID=peer0.org25.example.com
      - CORE_PEER_ADDRESS=peer0.org25.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org25.example.com:7051
      - CORE_PEER_LOCALMSPID=Org25MSP
      extends:
        file: peer-base.yaml
        service: peer-base
      ports:
      - 31051:7051
      - 31053:7053
      volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org25.example.com/peers/peer0.org25.example.com/msp:/etc/hyperledger/fabric/msp
      - peer0.org25.example.com:/var/hyperledger/production

